### ISSUE TITLE
Update README on mongo-collection-instances

### ISSUE THREAD

**Issue by dandv** [rclai/meteor-collection-extensions#4]
>  I will fork major packages like matb33:collection-hooks, sewdn:collection-behaviours, dburles:mongo-collection-instances, refactor the code to use this utility package

This was already done (thanks, BTW!)

**Comment by rclai** [comment]
It's not on collection hooks, yet. And sewdn hasn't accepted my PR. I think @zimme might start using it though. Has the collection organization been started yet?

I'm still having trouble making sure that `Meteor.users instanceof Mongo.Collection`, mainly because of the way the prototype is replaced. I don't know if it's possible to achieve (IE < 10 seem to be having trouble). If you have a clue, how to achieve that, that would be great. And actually, @matb33, if you know how that would great too.

**Comment by dandv** [comment]
Uh, I meant this was done in `mongo-collection-instances`.
