### ISSUE TITLE
Meteor.Collection !== Meteor.Collection.prototype.constructor

### ISSUE THREAD

**Issue by vsivsi** [rclai/meteor-collection-extensions#6]
After loading this package, the `Meteor.Collection` object is left halfway between the old state and the extended state. Any package that extends the patched `Meteor.Collection` using prototype inheritance, such as using Coffeescript [class / extends](http://coffeescript.org/#classes) will fail to use the monkey-patched constructor.

Here's the issue where I discovered this: https://github.com/vsivsi/meteor-file-sample-app/issues/2#issuecomment-120780592

I'm not embarrassed to say that I'm pretty opinionated about this, and I'm going to add more sanity checks and throws to my packages to defend against other packages that misbehave when replacing Meteor provided standard system calls.

IMO, the safe and sane way to extend `Mongo.Collection` is via a mechanism that supports, e.g.:

```js
extendedCollection = collectionExtend(Mongo.Collection, methods);
collection = new extendedCollection('foo');
extraExtendedCollection = collectionExtend(extendedCollection, methods);
collection2 = new extraExtendedCollection('bar');
```

If the app developer wants the "convenience" of setting `Mongo.Collection = extraExtendedCollection` then let that be *their* choice.

**Comment by rclai** [comment]
I totally get your pain. I'm not a big fan of this monkey-patching business, which is one of the reasons that I wanted to create this package, so that the blame can get pointed to one destination, instead of many, until a more suitable solution is available.

There is a Meteor [issue](https://github.com/meteor/meteor/issues/395) pending to be addressed for a better solution of extending `Mongo.Collection`.

I agree with the implementation that you suggest there, but that would result in a Meteor-community-sized shockwave of doom. There are numerous packages that depend on `dburles:mongo-collection-instances`, which depends on this. The only reasonable thing I can do is patch up this [here](https://github.com/rclai/meteor-collection-extensions/blob/master/collection-extensions.js#L77), by adding `ns.Collection.prototype.constructor = ns.Collection`.

Aside from this, if this issue stems from Coffeescript using `class.prototype.constructor` as `__super__`, does that also mean that @matb33's `matb33:collection-hooks` also faces this issue in this [section of code](https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L182-L202)?

**Comment by rclai** [comment]
I've created a [PR](https://github.com/rclai/meteor-collection-extensions/pull/8). Let me know if this works.
